import Head from 'next/head'
import Navbar from '/components/Navbar'
import Search from '/components/Search'
import Login from '/components/loginTest'

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Search/>
      <Login/>
    </>
  )
}
